name: Notifier

on:
  workflow_dispatch: 

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Send GroupMe notification
      env:
        GROUPME_BOT: ${{ secrets.GROUPME_BOT }}
        GROUPME_KEY: ${{ secrets.GROUPME_KEY }}
        GROUPME_GROUP_ID: ${{ secrets.GROUPME_GROUP_ID }}
        GROUPME_ALIVE: ${{ secrets.GROUPME_ALIVE }}
      run: |
        python -m alphonse
